### ISSUE TITLE
retry notarytool on flakes

### ISSUE THREAD

**Issue by lopopolo** [artichoke/nightly#129]
Check for error output and retry this command which executes over the network.

See failed runs for examples:

- https://github.com/artichoke/nightly/actions/runs/3963549019/jobs/6791505870

```
Error: failed to invoke command
    Command: ['/usr/bin/xcrun', 'notarytool', 'store-credentials', 'artichoke-apple-codesign-notarize', '--apple-id', 'apple-codesign@artichokeruby.org', '--password', '***', '--team-id', 'VDKP67932G', '--keychain', '/Users/runner/work/_temp/notarization.keychain-db']
    Return Code: 1
Output:
    Error: HTTP status code: 500. Internal Server Error
    
    Request ID: 33MG5MVHH66EFWISZRN2C4FGQ4.0.0
     Please try again at a later time.
    
    This process stores your credentials securely in the Keychain. You reference these credentials later using a profile name.
    
    Validating your credentials...
Traceback (most recent call last):
  File "/Users/runner/work/nightly/nightly/macos_sign_and_notarize.py", line 821, in main
    setup_codesigning_and_notarization_keychain(keychain_password=keychain_password)
  File "/Users/runner/work/nightly/nightly/macos_sign_and_notarize.py", line 458, in setup_codesigning_and_notarization_keychain
    import_notarization_credentials()
  File "/Users/runner/work/nightly/nightly/macos_sign_and_notarize.py", line 354, in import_notarization_credentials
    run_command_with_merged_output(
  File "/Users/runner/work/nightly/nightly/macos_sign_and_notarize.py", line 34, in run_command_with_merged_output
    proc = subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/xcrun', 'notarytool', 'store-credentials', 'artichoke-apple-codesign-notarize', '--apple-id', 'apple-codesign@artichokeruby.org', '--password', '***', '--team-id', 'VDKP679[32](https://github.com/artichoke/nightly/actions/runs/3963549019/jobs/6791505870#step:15:33)G', '--keychain', '/Users/runner/work/_temp/notarization.keychain-db']' returned non-zero exit status 1.
```

**Comment by lopopolo** [comment]
got another flake today:

https://github.com/artichoke/nightly/actions/runs/4228053486/jobs/7343114110#step:15:254

Stack trace and error output:

```
Error: failed to invoke command
    Command: ['/usr/bin/xcrun', 'notarytool', 'submit', PosixPath('dist/artichoke-nightly-aarch64-apple-darwin.dmg'), '--keychain-profile', 'artichoke-apple-codesign-notarize', '--keychain', '/Users/runner/work/_temp/notarization.keychain-db', '--wait']
    Return Code: 1
Output:
    Conducting pre-submission checks for artichoke-nightly-aarch64-apple-darwin.dmg and initiating connection to the Apple notary service...
    Submission ID received
      id: 677aa997-d14d-4df1-9dee-e5e6a0050c22
    Successfully uploaded file
      id: 677aa997-d14d-4df1-9dee-e5e6a0050c22
      path: /Users/runner/work/nightly/nightly/dist/artichoke-nightly-aarch64-apple-darwin.dmg
    Waiting for processing to complete.
    
    Current status: In Progress...
Error Output:
    Error: HTTP status code: 500. Internal Server Error
    
    Request ID: LPI5NRWRSQWKAAWO3U4TLLWM2U.0.0
     Please try again at a later time.
Traceback (most recent call last):
  File "/Users/runner/work/nightly/nightly/macos_sign_and_notarize.py", line 832, in main
    notarize_bundle(bundle=bundle)
  File "/Users/runner/work/nightly/nightly/macos_sign_and_notarize.py", line 642, in notarize_bundle
    proc = subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/xcrun', 'notarytool', 'submit', PosixPath('dist/artichoke-nightly-aarch64-apple-darwin.dmg'), '--keychain-profile', 'artichoke-apple-codesign-notarize', '--keychain', '/Users/runner/work/_temp/notarization.keychain-db', '--wait']' returned non-zero exit status 1.
```

**Comment by lopopolo** [comment]
got another one of these today. fix here:

- https://github.com/artichoke/nightly/pull/135
